### ISSUE TITLE
Realtime database is dead

### ISSUE THREAD

**Issue by clanoftheducks** [Zermelo-101/ScreenRecordApp#2]
:(
No alert on the dashboard, but neither Android not iOS app are uploading data. Probably something to do with rules being too permissive, cf dashboard alerts and emails in the past few days.

**Comment by clanoftheducks** [comment]
Actually it's not dead.
Can we keep pushing the rule expiration date eternally ?

**Comment by davethehacker** [comment]
I changed the expiry date for the public access to august, so it should be ok.
